// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugcplktphvsktuqbkall.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnY3Bsa3RwaHZza3R1cWJrYWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNzY4ODEsImV4cCI6MjA2Mjc1Mjg4MX0.CQjzOvZUtibNll_iTAIpYzBwywAfefFdg46w7wiqH8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);